### ISSUE TITLE
Sass error

### ISSUE THREAD

**Issue by marzyn** [icelam/random-name-picker#13]
ERROR in ./src/assets/scss/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!./src/assets/scss/index.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\input.js:24:13)
    at parse (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\parse.js:8:15)
    at new LazyResult (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\lazy-result.js:133:16)
    at Processor.process (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\processor.js:28:14)
    at Object.loader (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss-loader\dist\index.js:95:30)
 @ ./src/assets/scss/index.scss 8:6-285 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-255 83:0-255 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/index.ts 6:0-28

**Comment by icelam** [comment]
Hello @marzyn,

I apologize for the inconvenience you're experiencing. Unfortunately, I couldn't replicate the issue on my machine. However, I suspect that it could be due to a version conflict between postcss and node-sass.

To assist you better, could you kindly provide the following information? This will help me investigate the issue further:
1. **Operating System**: Please let me know the operating system you are using.
2. **Node.js Version**: Please provide the version of Node.js installed on your machine.
3. **Package Management Tools**: Please specify the package management tool you are using, such as yarn or npm.
4. **package.lock or yarn.lock**: If possible, please attach the package.lock or yarn.lock file here. This will help me analyze the dependencies more accurately.

Meanwhile, you can try visiting the following link to see if it helps solve the issue: [Vue2 - Error: PostCSS received undefined instead of CSS string](https://stackoverflow.com/questions/69012734/vue2-error-postcss-received-undefined-instead-of-css-string)

**Comment by longkiemphi** [comment]
> ERROR in ./src/assets/scss/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!./src/assets/scss/index.scss) Module build failed (from ./node_modules/postcss-loader/dist/cjs.js): Error: PostCSS received undefined instead of CSS string at new Input (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\input.js:24:13) at parse (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\parse.js:8:15) at new LazyResult (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\lazy-result.js:133:16) at Processor.process (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss\lib\processor.js:28:14) at Object.loader (D:\random-name-picker-1.2.0\random-name-picker-1.2.0\node_modules\postcss-loader\dist\index.js:95:30) @ ./src/assets/scss/index.scss 8:6-285 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-255 83:0-255 84:22-29 84:33-47 84:50-64 61:4-74:5 @ ./src/index.ts 6:0-28

You can use pnpm instead of yarrn, it work for me when I see this errors:

```
npm install -g pnpm
pnpm install

# dev
pnpm start
# build 
pnpm build
```

**Comment by icelam** [comment]
@marzyn, since I haven't received any updates from you, I will proceed to close this PR for now. In order to address your issue, I have taken the following steps:
- Upgraded the Node.js version from 14 to 18.
- Updated the package dependencies to their latest versions.
- Implemented a CI/CD pipeline to perform build checks on different operating systems (Linux, macOS, and Windows).

If you encounter any further issues, please feel free to reopen the PR. Your feedback is always welcome.

**Comment by marzyn** [comment]
Still having some promblem starting the app. on windows

**Comment by marzyn** [comment]
i got this error
![Screenshot 2024-08-29 094250](https://github.com/user-attachments/assets/9364e8b2-70be-4486-968a-5e4edacb3385)
