### ISSUE TITLE
Please provide installation instructions for newbies.

### ISSUE THREAD

**Issue by wpresources** [icelam/random-name-picker#16]
**1.I have uploaded the source code to CPanel**
![1](https://github.com/icelam/random-name-picker/assets/44034958/cbbcd191-8994-4938-9322-9cbc4dc19797)

**2.I have Setup Node Js**
![2](https://github.com/icelam/random-name-picker/assets/44034958/025dff08-6a6b-43f9-bd50-c2985d767155)

**3.Kết quả**
![3](https://github.com/icelam/random-name-picker/assets/44034958/8c12d27e-78c4-4aa6-b30c-374d28ea8575)

I want the same result as the demo.
https://[tag.intelmkt.top](https://tag.intelmkt.top/)/
https://pinkylam.me/playground/random-name-picker/

 How do I do it? Please help me

**Comment by icelam** [comment]
Hello @wpresources, instead of configuring CPanel to run Node.js, you will need to build and deploy the generated assets to the web server's public folder. Here are some some general guidance on how you can configure your deploy this app to a web server.

1. Set up your CI/CD pipeline to use Node.js and yarn images. (If you prefer not to use a CI/CD pipeline, make sure you have both Node.js and yarn installed on your machine.)

2. Start by installing the project dependencies. Run the command `yarn install` to ensure that all the necessary npm packages are installed and ready for the build process. To optimize costs and improve the efficiency of your CI/CD pipeline, you can consider adding a cache for the `node_modules` directory. Check your specific CI/CD tool's documentation for cache configuration options.

3. Next, you'll need to build the project. Use the command `yarn build` to initiate the build process. This command will compile and bundle the source code, generating the assets required for hosting.

4. Once the build process is complete, you'll need to copy all the generated assets from the `/dist` directory. The specific command for this step may vary depending on your CI/CD tool and operating system. Typically, you'll include a pipeline step that copies the contents of the `/dist` directory to web server's public folder.
