### ISSUE TITLE
Uncaught runtime errors when sound effect is being play

### ISSUE THREAD

**Issue by singsingwong2** [icelam/random-name-picker#23]
After clone the repo and install with yarn, I can start the server by yarn start. But whenever a sound is being play on the page, an uncaught error is occurred.

Uncaught runtime errors:
×
ERROR
Invalid or unexpected token
SyntaxError: Invalid or unexpected token
    at XH (<anonymous>:1:788)
    at <anonymous>:1:3077
    at Array.map (<anonymous>)
    at QG.VX.z (<anonymous>:1:3071)
    at Ze (<anonymous>:1:1021)
    at XH (<anonymous>:1:788)
    at <anonymous>:1:3188

## Environment

1. Install and start the server
2. After page is loaded on browser, go to setting to enter few names in Name List
3. Ensure the sound effect
4. Save setting
5. Press "Draw" button
6. Lucky draw start but a pop up dialog box show up the runtime error.

## What is expected?

Expect sound will be played without runtime error.

## What is actually happening?

A pop up dialog box show up the runtime error.

**Comment by icelam** [comment]
Hello @singsingwong2 ,

I apologize for the inconvenience you're experiencing. Unfortunately, I couldn't replicate the issue on my machine. To assist you better, could you kindly provide the following information? This will help me investigate the issue further:

1. **Operating System**: Please let me know the operating system you are using.
2. **Node.js Version**: Please provide the version of Node.js installed on your machine.
3. **Browser Version**: Please let me know the version of browser you are using. 
4. **Screenshot of the dev tool**: To better understand the error message and the problematic source code, please provide some screenshots of the browser's Dev Tools. It will be best if you can screenshot the **unminified** source code which causes the error.

I'll do my best to help you resolve the issue.

**Comment by singsingwong2** [comment]
That's strange. Information lost when I submit the issue report. Here are the information. 

OS: 
Edition	Windows 10 Pro
Version	21H1
Installed on	‎9 ‎Dec ‎2021
OS build	19043.1387
Experience	Windows Feature Experience Pack 120.2212.3920.0

Node.js: v18.15.0
Browser Version: 121.0.6167.140 (Official Build) (64-bit)

![image](https://github.com/icelam/random-name-picker/assets/4525213/63a5d54c-6a9f-48c1-8a77-54eebbf5f303)
![image](https://github.com/icelam/random-name-picker/assets/4525213/3473377d-4db0-4c7a-9964-7cfd66a66544)

**Comment by icelam** [comment]
Hi @singsingwong2,

Based on the screenshots you provided, I wasn't able to identify the problematic code. However, the error message suggests that there might be a syntax error in an anonymous function called by `Array.map`. It doesn't appear to be part of the source code of this app.

I attempted to replicate the issue on my Windows 10 Virtual Machine with Node.js v18.15.0, but I was unable to do so. The lucky draw runs successfully with and without sound effect enabled.
<img src="https://github.com/icelam/random-name-picker/assets/6780420/f24297b9-8191-469d-b76c-9ba44459c798">

I suspect that the problem could be caused by one of the following:
1. Browser plugins: There may be certain browser plugins that are interfering with the execution of the code. To debug the issue, you may want to try running the app under incognito mode without any plugins enabled, or simply use another browser.
2. Project dependencies: It's possible that the error is related to the dependencies (node_modules) of the project. I am not too sure about this since the stack trace of the error message is showing minified function names, and is not showing the filename or line number of the code causing the problem.The file `prompt.js` shown in the second screenshot you provided doesn't seems to be belong to any node_modules, it would help if you can provide the full path of the file.
<img width="528" alt="Screenshot 2024-02-06 at 10 55 17 PM" src="https://github.com/icelam/random-name-picker/assets/6780420/d55a6127-8de9-458c-bd77-5afcbebb75ee">

3. Custom code recently added: If you have added or modified any part of the source code, it could be the source of issue. Is there any changes made to the source code?

**Comment by singsingwong2** [comment]
Thanks for your suggestion. Finally, I find out a plugin "modheader" is the root cause. After turning it off, everything is normal now. Thanks.

**Comment by icelam** [comment]
Glad to hear that my suggestions have been helpful. If you need further assistance, don't hesitate to ask.
