### ISSUE TITLE
Help, Deploying Locally in Ubuntu

### ISSUE THREAD

**Issue by iAsk111** [icelam/random-name-picker#33]
Hello

Need a bit of assistance here, not an expert on this but I was trying to run your code locally in an ubuntu machine.
I manage to install NodeJS/NPM and Yarn. When I try to start Yarn, it gave me the following error.
It fails to build it, something about node_modules?.

Thanks in advanced.

```
/home/itech/.cache/node-gyp/22.11.0/include/node/node.h:1266:3: note: in expansion of macro ‘NODE_MODULE_X’
 1266 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’
  358 | NODE_MODULE(binding, RegisterModule);
      | ^~~~~~~~~~~
make: *** [binding.target.mk:128: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/itech/Downloads/random-name-picker-2.1.0/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/itech/Downloads/random-name-picker-2.1.0/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 6.8.0-41-generic
gyp ERR! command "/usr/local/bin/node" "/home/itech/Downloads/random-name-picker-2.1.0/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/itech/Downloads/random-name-picker-2.1.0/node_modules/node-sass
gyp ERR! node -v v22.11.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
Build failed with error code: 1
```

**Comment by icelam** [comment]
Hi @iAsk111, 

I'm sorry to hear you're having trouble setting up the project. The stack trace you provided is very helpful in diagnosing the issue.

It appears that the error is caused by an incompatible version of `node-sass` with the Node.js version installed on your machine. This project is compatible with Node.js 20, but it seems to be having issues with version 22.11.0.

Since `node-sass` is deprecated, I plan to transition to the `sass` package, but this will take some time. In the meantime, here are some solutions you can try:
1. Install NVM. This tool allows you to manage and switch between different Node.js versions, which should allow you to install Node.js 20 easily.
2. If you have experience in frontend development, consider replacing `node-sass` with the `sass` package and updating `sass-loader` to the latest version.

Thank you for your understanding, and I appreciate your patience as I work on a fix!

**Comment by iAsk111** [comment]
Hey there
Thanks for the feedback.... Yes, I installed a lower version of nodejs, V19 just to be safe, I installed it on a windows 10 machine.
It is working now, since there are changes on node (sass) to be precise.
No worries, take your time, I'm using your code as of now.
Just need some help on the audio side.
Thanks
